### ISSUE TITLE
Segmentation fault on summit at olcf

### ISSUE THREAD

**Issue by khou2020** [uiuc-hpc/Recorder#16]
I tried to use recorder to study a performance issue I encountered on summit at olcf.
I can build the library following the instruction, but it crashed after being injected into my application.

The core file shows it repeatedly calls MPI_Init and overflowed the stack. Seems it fails to find real MPI functions.
#0  0x00002000000ffedc in PMPI_Init (argc=0x0, argv=0x0) at /ccs/home/khl7265/csc332/Recorder/lib/recorder-init-finalize.c:85
#1  0x00002000000fff64 in PMPI_Init (argc=0x7ffff1366210, argv=0x7ffff1366218) at /ccs/home/khl7265/csc332/Recorder/lib/recorder-init-finalize.c:87
#2  0x00002000000fff64 in PMPI_Init (argc=0x7ffff1366210, argv=0x7ffff1366218) at /ccs/home/khl7265/csc332/Recorder/lib/recorder-init-finalize.c:87

The build environment was:
  1) xl/16.1.1-10   2) spectrum-mpi/10.4.0.3-20210112   3) lsf-tools/2.0   4) hsi/5.0.2.p5   5) darshan-runtime/3.3.0-lite   6) xalt/1.2.1   7) DefApps   8) cmake/3.21.3

Cmake options are:
BUILD_SHARED_LIBS:BOOL=ON
BUILD_TESTING:BOOL=ON
CMAKE_ADDR2LINE:FILEPATH=/usr/bin/addr2line
CMAKE_AR:FILEPATH=/usr/bin/ar
CMAKE_ARCHIVE_OUTPUT_DIRECTORY:PATH=/ccs/home/khl7265/csc332/Recorder/build/bin
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_CXX_COMPILER:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/xl-16.1.1-10/spectrum-mpi-10.4.0.3-20210112-dzedzfvocsuzkm4jkqe7o64x53yhq7nm/bin/mpic++
CMAKE_CXX_FLAGS_DEBUG:STRING=-g -g3
CMAKE_C_COMPILER:STRING=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/xl-16.1.1-10/spectrum-mpi-10.4.0.3-20210112-dzedzfvocsuzkm4jkqe7o64x53yhq7nm/bin/mpicc
CMAKE_C_FLAGS_DEBUG:STRING=-g -g3
CMAKE_DLLTOOL:FILEPATH=CMAKE_DLLTOOL-NOTFOUND
HDF5_C_COMPILER_EXECUTABLE:FILEPATH=/ccs/home/khl7265/csc332/.local/hdf5/develop/bin/h5pcc
HDF5_C_LIBRARY_dl:FILEPATH=/usr/lib64/libdl.so
HDF5_C_LIBRARY_hdf5:FILEPATH=/ccs/home/khl7265/csc332/.local/hdf5/develop/lib/libhdf5.so
HDF5_C_LIBRARY_m:FILEPATH=/usr/lib64/libm.so
HDF5_C_LIBRARY_z:FILEPATH=/usr/lib64/libz.so
HDF5_DIFF_EXECUTABLE:FILEPATH=/ccs/home/khl7265/csc332/.local/hdf5/develop/bin/h5diff
HDF5_DIR:PATH=HDF5_DIR-NOTFOUND
MPI_CXX_COMPILER:FILEPATH=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/xl-16.1.1-10/spectrum-mpi-10.4.0.3-20210112-dzedzfvocsuzkm4jkqe7o64x53yhq7nm/bin/mpic++
MPI_C_COMPILER:FILEPATH=/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/xl-16.1.1-10/spectrum-mpi-10.4.0.3-20210112-dzedzfvocsuzkm4jkqe7o64x53yhq7nm/bin/mpicc
RECORDER_ENABLE_CUDA_TRACE:BOOL=OFF
RECORDER_ENABLE_FCNTL_TRACE:BOOL=ON
RECORDER_ENABLE_HDF5_TRACE:BOOL=ON
RECORDER_ENABLE_MPIO_TRACE:BOOL=ON
RECORDER_ENABLE_PARQUET:BOOL=OFF
RECORDER_ENABLE_POSIX_TRACE:BOOL=ON

**Comment by wangvsa** [comment]
Hi, it is likely due to the conflict between Recorder and Darshan. Both use the same mechanism for intercepting calls. Recorder and Darshan can not be used in the same time. Can you try unload darshan modules and make sure darshan is not linked with your app (use ldd to find out)?

**Comment by khou2020** [comment]
That works, thanks.
