### ISSUE TITLE
question about starts_first/last in overlap test

### ISSUE THREAD

**Issue by adammoody** [uiuc-hpc/Recorder#17]
I was browsing the code that identifies potential conflicts.  If ``i1->tstart == i2->tstart``, I think the lines below would assign ``i2`` to both ``start_first`` and ``starts_last``.  Is it possible for those to be equal, and if so, do you want to assign ``i1`` to on of those values instead?

https://github.com/uiuc-hpc/Recorder/blob/8f02a004081fb6f07d764c2d21b3dd791d5eee67/tools/overlap_conflict.c#L135-L136

**Comment by wangvsa** [comment]
Assuming i1->tstart == i2->tstart, then there is certainly no commit/close-to-open operations in between. In other words, i1 conflicts i2 no matter the consistency semantics.

Even though in this case both starts_first and starts_later are i2, the below code still guarantees conflicts = true for commit semantics and session semantics. But I should check that in the case of POSIX consistency. 

// for commit semantics, next_commit is always > starts_later->tstart
https://github.com/uiuc-hpc/Recorder/blob/8f02a004081fb6f07d764c2d21b3dd791d5eee67/tools/overlap_conflict.c#L148

// for session semantics, next_close is always > prev_open
https://github.com/uiuc-hpc/Recorder/blob/8f02a004081fb6f07d764c2d21b3dd791d5eee67/tools/overlap_conflict.c#L158

**Comment by adammoody** [comment]
Ok, thanks for the explanation, @wangvsa .  I didn't take the time to check things in detail.  It's just that the comparison checks looked a little suspicious.  I was wondering if one of those lines should use something like ``<=`` instead of ``<``:
```
 Interval *starts_first = (i1->tstart <= i2->tstart) ? i1 : i2; 
 Interval *starts_later = (i1->tstart >  i2->tstart) ? i1 : i2;
```
That would ensure that ``starts_first`` and ``starts_last`` are always different, but then I don't know if that would break things later on.  Anyway, it sounds like it's not needed.

**Comment by wangvsa** [comment]
I agree, it think its better to change it to <=, it's easier to understand the code in the future.
Code updated in the latest commit: https://github.com/uiuc-hpc/Recorder/commit/00040d9f1d3dcc3111297e5002376b4e89a93fdf
